#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.150.0.254 dev net0
[ ! -e "/root/.ethereum/geth/nodekey" ] && geth --datadir /root/.ethereum init /tmp/eth-genesis.json
cp /tmp/keystore/UTC--2023-03-02T12-56-16.365162000Z--0x8c400205fDb103431F6aC7409655ad3cf8f6d007 /root/.ethereum/keystore/
cp /tmp/keystore/UTC--2023-03-02T12-56-44.167013000Z--0x9105A373ce1d01B517aA54205A5E4c70FA9f34Fe /root/.ethereum/keystore/
chmod +x /tmp/eth-bootstrapper
/tmp/eth-bootstrapper
geth --datadir /root/.ethereum --identity="NODE_3" --networkid=1337 --syncmode full --snapshot=False --verbosity=2 --allow-insecure-unlock --port 30303 --bootnodes "$(cat /tmp/eth-node-urls)" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api web3,eth,debug,personal,net,clique,engine,admin,txpool --unlock "0x8c400205fDb103431F6aC7409655ad3cf8f6d007, 0x9105A373ce1d01B517aA54205A5E4c70FA9f34Fe" --password "/tmp/eth-password"                             &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

